- applescript
- actionscript3
- coldfusion
- c
- csharp
- css
- delphi
- diff
- erlang
- groovy
- java
- javafx
- javascript
- pascal
- perl
- php
- python
- ruby
- sass
- scala
- shell
- sql
- text
- vbnet
- xml